/* Word usage: prepositions and collocations per word, keyed by card id (set||term, lowercased).
   Generated in a Claude session; see tools/validate_usage.js. Words with nothing worth teaching are absent. */
const WORD_USAGE = {
"2026||supplicate": {"use":["supplicate (someone) for (something)"],"ex":"The villagers came to supplicate the king for mercy."},
"2026||extrajudicial": {"use":["extrajudicial killing","extrajudicial punishment"],"ex":"Human rights groups condemned the extrajudicial killing of protesters."},
"2026||harbinger": {"use":["harbinger of (change, doom)"],"ex":"Early snow was a harbinger of a harsh winter."},
"2026||sundry": {"use":["all and sundry","sundry items"],"ex":"He invited all and sundry to the opening."},
"2026||gaffe": {"use":["make a gaffe","commit a gaffe"],"ex":"Try not to make a gaffe in front of the board."},
"2026||diffident": {"use":["diffident about (one's abilities)"],"ex":"She felt diffident about presenting her own work."},
"2026||incommensurable": {"use":["incommensurable with (something)"],"ex":"The two worldviews are incommensurable with each other."},
"2026||dispositive": {"use":["dispositive of (a case)","dispositive motion"],"ex":"The ruling was dispositive of the entire claim."},
"2026||senescence": {"use":["cellular senescence"],"ex":"Researchers study cellular senescence to understand aging."},
"2026||insouciance": {"use":["with insouciance","an air of insouciance"],"ex":"He shrugged off the criticism with insouciance."},
"2026||mendicant": {"use":["mendicant friar","mendicant order"],"ex":"The mendicant friars lived on donated food."},
"2026||abridge": {"use":["abridge (a text)","abridged edition"],"ex":"Publishers often abridge long novels for young readers."},
"2026||neologism": {"use":["coin a neologism"],"ex":"Writers sometimes coin a neologism when no word fits."},
"2026||divination": {"use":["divination by (tea leaves, cards)"],"ex":"Some cultures practiced divination by reading animal bones."},
"2026||coterie": {"use":["coterie of (friends, advisers)"],"ex":"A small coterie of advisers surrounded the mayor."},
"2026||retinue": {"use":["retinue of (servants)","with a retinue"],"ex":"The ambassador arrived with a retinue of assistants."},
"2026||acolyte": {"use":["acolyte of (a leader)"],"ex":"He was an acolyte of the famous chef."},
"2026||chimera": {"use":["chase a chimera","pursue a chimera"],"ex":"Investors who chase a chimera rarely profit."},
"2026||imbibe": {"use":["imbibe (a drink)","imbibe (ideas, values)"],"ex":"Children imbibe their parents' values without noticing."},
"2026||callous": {"use":["callous to (suffering)","callous disregard for (others)"],"ex":"He grew callous to the suffering around him."},
"2026||dialectic": {"use":["dialectic between (two forces)"],"ex":"The novel explores the dialectic between freedom and duty."},
"2026||bricolage": {"use":["bricolage of (styles)"],"ex":"The album is a bricolage of jazz, folk and electronic sounds."},
"2026||synoptic": {"use":["synoptic view","Synoptic Gospels"],"ex":"The chapter gives a synoptic view of the whole war."},
"2025||vaunt": {"use":["vaunt (one's achievements)","much vaunted"],"ex":"The firm likes to vaunt its safety record."},
"2025||contravene": {"use":["contravene (a rule, a law)","in contravention of (a rule)"],"ex":"The new policy would contravene existing safety laws."},
"2025||bustle": {"use":["bustle about","bustle with (activity)","hustle and bustle"],"ex":"Staff began to bustle about the kitchen before dawn."},
"2025||ensconce": {"use":["ensconced in (a place)"],"ex":"She was ensconced in an armchair by the fire."},
"2025||disconsolate": {"use":["disconsolate over (a loss)"],"ex":"He was disconsolate over the team's defeat."},
"2025||sardonic": {"use":["sardonic smile","sardonic humor"],"ex":"A sardonic smile crossed his face."},
"2025||autarky": {"use":["pursue autarky","economic autarky"],"ex":"Some regimes pursue autarky to avoid foreign dependence."},
"2025||contrition": {"use":["contrition for (a wrong)","act of contrition"],"ex":"He expressed deep contrition for his mistake."},
"2025||spurn": {"use":["spurn (an offer)","spurn (someone's advances)"],"ex":"Do not spurn an offer of help."},
"2025||supercilious": {"use":["supercilious air","supercilious smile"],"ex":"He spoke with a supercilious air."},
"2025||blather": {"use":["blather on (about something)"],"ex":"He would blather on about politics for hours."},
"2025||torpor": {"use":["fall into torpor","lapse into torpor"],"ex":"Bears fall into torpor during the coldest months."},
"2025||bonhomie": {"use":["with bonhomie","an air of bonhomie"],"ex":"He greeted every guest with bonhomie."},
"2025||torrid": {"use":["have a torrid time","torrid affair"],"ex":"Expect to have a torrid time in the first round."},
"2025||contradistinction": {"use":["in contradistinction to (something)"],"ex":"Art, in contradistinction to craft, aims at expression."},
"2025||pecuniary": {"use":["pecuniary interest","pecuniary gain"],"ex":"He had no pecuniary interest in the deal."},
"2025||rote": {"use":["by rote","rote learning"],"ex":"Students learned the dates by rote."},
"2025||cinch": {"use":["be a cinch (to do something)","a cinch for (someone)"],"ex":"It should be a cinch to finish by noon."},
"2025||apposite": {"use":["apposite to (a subject)"],"ex":"Her remark was apposite to the discussion."},
"2025||agglomerate": {"use":["agglomerate into (a mass)"],"ex":"Small particles agglomerate into larger clumps."},
"2025||hypothecate": {"use":["hypothecated tax","hypothecate (revenue) to (a purpose)"],"ex":"Most governments avoid a hypothecated tax for general spending."},
"2025||devolution": {"use":["devolution of (power) to (a region)"],"ex":"Voters backed the devolution of power to Scotland."},
"2025||coterminous": {"use":["coterminous with (something)"],"ex":"The parish is coterminous with the old village boundary."},
"2025||entrepot": {"use":["entrepot trade"],"ex":"Hong Kong grew rich on entrepot trade."},
"2025||cogitate": {"use":["cogitate on (a problem)","cogitate over (a decision)"],"ex":"He sat down to cogitate on the problem."},
"2024||transpose": {"use":["transpose into (another key)","transpose (one thing) with (another)"],"ex":"Singers often transpose the melody into a lower key."},
"2024||truancy": {"use":["truancy officer","chronic truancy"],"ex":"The truancy officer visited the family twice."},
"2024||efface": {"use":["efface (oneself)","efface (a memory)"],"ex":"She tried to efface herself in the crowd."},
"2024||peremptory": {"use":["peremptory tone","peremptory challenge"],"ex":"He ordered them out in a peremptory tone."},
"2024||aleatory": {"use":["aleatory music"],"ex":"The composer wrote aleatory music that changes every performance."},
"2024||manifold": {"use":["manifold (benefits, reasons)"],"ex":"The benefits of exercise are manifold."},
"2024||depravity": {"use":["moral depravity","depravity of (a crime)"],"ex":"The judge spoke of the moral depravity of the crime."},
"2024||mire": {"use":["mired in (debt, controversy)","drag (someone) through the mire"],"ex":"The company is mired in debt."},
"2024||solemn": {"use":["solemn oath","solemn vow"],"ex":"She swore a solemn oath to protect them."},
"2024||concomitant": {"use":["concomitant with (something)"],"ex":"Rising prices are concomitant with higher demand."},
"2024||ire": {"use":["draw the ire of (someone)","incur (someone's) ire"],"ex":"The decision will draw the ire of local voters."},
"2024||malignant": {"use":["malignant tumor","malignant influence"],"ex":"Doctors found a malignant tumor."},
"2024||precipitate": {"use":["precipitate (a crisis)","precipitate (someone) into (a state)"],"ex":"A single insult could precipitate a crisis."},
"2024||rescission": {"use":["rescission of (a contract)"],"ex":"He sought rescission of the lease."},
"2024||adduce": {"use":["adduce (evidence)","adduce (an argument) in support of (a claim)"],"ex":"Lawyers must adduce evidence in support of their claims."},
"2024||incontrovertible": {"use":["incontrovertible evidence","incontrovertible proof"],"ex":"The video offered incontrovertible evidence of the theft."},
"2024||execrable": {"use":["execrable taste"],"ex":"Critics mocked the film for its execrable taste."},
"2024||jubilant": {"use":["jubilant over (a win)","jubilant at (the news)"],"ex":"Fans were jubilant over the late goal."},
"2024||supererogatory": {"use":["supererogatory act"],"ex":"Donating a kidney is a supererogatory act."},
"2024||actuate": {"use":["actuated by (a motive)","actuate (a mechanism)"],"ex":"He was actuated by greed."},
"2024||upbraid": {"use":["upbraid (someone) for (a mistake)"],"ex":"The coach would upbraid players for careless errors."},
"2024||pilfer": {"use":["pilfer (something) from (a place)"],"ex":"Employees were caught trying to pilfer supplies from the warehouse."},
"2024||euphemism": {"use":["euphemism for (something)"],"ex":"Let go is a common euphemism for fired."},
"2024||propound": {"use":["propound (a theory)"],"ex":"Philosophers propound theories about justice."},
"2024||requisition": {"use":["requisition (supplies) from (someone)","requisition for (supplies)"],"ex":"Officers may requisition supplies from local farms."},
"2024||ineluctable": {"use":["ineluctable conclusion"],"ex":"The facts lead to an ineluctable conclusion."},
"2024||invective": {"use":["hurl invective at (someone)","a torrent of invective"],"ex":"Critics continued to hurl invective at the referee."},
"2024||interstice": {"use":["interstice between (two things)","in the interstices of (a system)"],"ex":"Weeds grew in the interstice between two stones."},
"2024||disavow": {"use":["disavow (any knowledge of)","disavow (any connection with)"],"ex":"The senator will disavow any knowledge of the scheme."},
"2024||arrogate": {"use":["arrogate (a right) to (oneself)"],"ex":"Leaders should not arrogate power to themselves."},
"2024||atavistic": {"use":["atavistic fear","atavistic instinct"],"ex":"An atavistic fear of the dark kept her awake."},
"2024||spurious": {"use":["spurious correlation","spurious claim"],"ex":"The study found only a spurious correlation."},
"2024||talisman": {"use":["talisman against (harm)","lucky talisman"],"ex":"She wore a talisman against bad luck."},
"2024||inane": {"use":["inane remark","inane chatter"],"ex":"His inane remark ended the conversation."},
"2024||redoubtable": {"use":["redoubtable opponent","redoubtable reputation"],"ex":"She was a redoubtable opponent in debate."},
"2024||vitiate": {"use":["vitiated by (a flaw)","vitiate (a contract)"],"ex":"The whole study was vitiated by bias."},
"2024||tact": {"use":["with tact","tact and diplomacy"],"ex":"He broke the news with tact."},
"2024||obviate": {"use":["obviate the need for (something)"],"ex":"A better design could obviate the need for repairs."},
"2024||ethereal": {"use":["ethereal beauty","ethereal voice"],"ex":"Her ethereal beauty drew every eye in the room."},
"2024||ebullient": {"use":["ebullient about (a prospect)","ebullient mood"],"ex":"She was ebullient about the new job."},
"2024||jockey": {"use":["jockey for (position)"],"ex":"Rivals jockey for position before the vote."},
"2024||fester": {"use":["festering resentment","festering wound"],"ex":"Festering resentment slowly poisoned the team."},
"2024||remit": {"use":["within (one's) remit","beyond the remit of (a group)"],"ex":"Staffing is not within our remit."},
"2023||derelict": {"use":["derelict in (one's duty)","derelict building"],"ex":"The guard was derelict in his duty."},
"2023||condign": {"use":["condign punishment"],"ex":"The court imposed condign punishment on the offenders."},
"2023||veritable": {"use":["a veritable (feast, army)"],"ex":"The market was a veritable feast for the senses."},
"2023||privity": {"use":["privity of contract"],"ex":"Only parties in privity of contract can sue."},
"2023||mar": {"use":["marred by (a flaw)","mar (someone's) enjoyment"],"ex":"The event was marred by bad weather."},
"2023||lambaste": {"use":["lambaste (someone) for (a decision)"],"ex":"Critics will lambaste the mayor for the delay."},
"2023||protract": {"use":["protracted negotiations","protracted dispute"],"ex":"Protracted negotiations dragged on for months."},
"2023||indemnify": {"use":["indemnify (someone) against (loss)","indemnify (someone) for (damage)"],"ex":"The contract will indemnify the buyer against any loss."},
"2023||corrugate": {"use":["corrugated iron","corrugated cardboard"],"ex":"The shed had a corrugated iron roof."},
"2023||interminable": {"use":["interminable wait","interminable meeting"],"ex":"After an interminable wait, the doors finally opened."},
"2023||sordid": {"use":["sordid affair","sordid details"],"ex":"The sordid affair ruined his career."},
"2023||interpose": {"use":["interpose between (two things)","interpose (an objection)"],"ex":"She tried to interpose herself between the two men."},
"2023||vapid": {"use":["vapid conversation"],"ex":"The party was full of vapid conversation."},
"2023||fulminate": {"use":["fulminate against (a policy)"],"ex":"He loved to fulminate against modern manners."},
"2023||sinecure": {"use":["hold a sinecure"],"ex":"He managed to hold a sinecure for twenty years."},
"2023||anathema": {"use":["anathema to (someone)"],"ex":"Such compromise is anathema to hardliners."},
"2023||perfunctory": {"use":["perfunctory glance","perfunctory inspection"],"ex":"He gave the report only a perfunctory glance."},
"2023||motley": {"use":["motley crew","a motley collection of (things)"],"ex":"A motley crew of volunteers cleaned the beach."},
"2023||terse": {"use":["terse reply","terse statement"],"ex":"She sent a terse reply to the offer."},
"2023||abrogation": {"use":["abrogation of (a treaty)"],"ex":"The abrogation of the treaty angered allies."},
"2023||invidious": {"use":["invidious comparison","invidious distinction"],"ex":"It would be an invidious comparison to rank the two."},
"2023||virulent": {"use":["virulent strain","virulent criticism"],"ex":"A virulent strain of the flu spread through the school."},
"2023||rive": {"use":["riven by (conflict)"],"ex":"The party was riven by bitter factions."},
"2023||enjoin": {"use":["enjoin (someone) from (doing something)","enjoin (someone) to (do something)"],"ex":"The court may enjoin the company from selling the product."},
"2023||transmute": {"use":["transmute (lead) into (gold)"],"ex":"Alchemists hoped to transmute lead into gold."},
"2023||rapprochement": {"use":["rapprochement between (two countries)","rapprochement with (a rival)"],"ex":"A rapprochement between the two nations seemed likely."},
"2023||forbear": {"use":["forbear from (doing something)"],"ex":"Please forbear from interrupting the speaker."},
"2023||reprove": {"use":["reprove (someone) for (rudeness)"],"ex":"The teacher had to reprove him for his rudeness."},
"2023||repudiate": {"use":["repudiate (a claim)","repudiate (a debt)"],"ex":"Leaders must repudiate violence in all its forms."},
"2023||remuneration": {"use":["remuneration for (work)","adequate remuneration"],"ex":"He received no remuneration for his work."},
"2023||querulous": {"use":["querulous tone","querulous voice"],"ex":"She answered in a querulous tone."},
"2023||opprobrium": {"use":["public opprobrium","the opprobrium of (one's peers)"],"ex":"He faced public opprobrium after the scandal."},
"2023||recompense": {"use":["recompense (someone) for (a loss)","in recompense for (a loss)"],"ex":"The firm will recompense workers for lost wages."},
"2023||disinterested": {"use":["disinterested observer","disinterested party"],"ex":"A disinterested observer would call it a draw."},
"2023||impel": {"use":["impel (someone) to (act)"],"ex":"Hunger may impel people to steal."},
"2023||travail": {"use":["the travails of (someone)"],"ex":"The film follows the travails of a young migrant."},
"2023||ennui": {"use":["a feeling of ennui","ennui with (life)"],"ex":"A feeling of ennui settled over the town."},
"2023||facile": {"use":["facile answer","facile comparison"],"ex":"He gave a facile answer to a hard question."},
"2023||tract": {"use":["tract of (land)"],"ex":"The company bought a large tract of land."},
"2023||compunction": {"use":["without compunction","no compunction about (doing something)"],"ex":"He lied to them without compunction."},
"2023||fatuous": {"use":["fatuous remark","fatuous grin"],"ex":"He made a fatuous remark about the weather."},
"2023||encomium": {"use":["deliver an encomium","encomium for (a person)"],"ex":"She was asked to deliver an encomium at the ceremony."},
"2023||blithely": {"use":["blithely ignore (a warning)","blithely unaware of (a danger)"],"ex":"Drivers blithely ignore the speed limit."},
"2023||redolent": {"use":["redolent of (the past)"],"ex":"The room was redolent of old books."},
"2023||demur": {"use":["demur at (a request)","without demur"],"ex":"He did not demur at the request."},
"2023||disabuse": {"use":["disabuse (someone) of (a notion)"],"ex":"Nothing could disabuse him of that notion."},
"2023||inure": {"use":["inured to (hardship)","inure (someone) to (pain)"],"ex":"Soldiers become inured to hardship."},
"2023||impute": {"use":["impute (a motive) to (someone)"],"ex":"Do not impute bad motives to your rivals."},
"2023||consonance": {"use":["in consonance with (something)"],"ex":"His actions were in consonance with his beliefs."},
"2023||consecrate": {"use":["consecrate (a church)","consecrated to (a cause)"],"ex":"The bishop will consecrate the new chapel."},
"2023||arrear": {"use":["in arrears","in arrears on (rent)"],"ex":"The tenant fell in arrears on the rent."},
"2023||preponderate": {"use":["preponderate over (something)"],"ex":"In the sample, positive reviews preponderate over negative ones."},
"2023||disquiet": {"use":["a sense of disquiet","disquiet over (a decision)"],"ex":"A sense of disquiet spread through the office."},
"2023||diatribe": {"use":["diatribe against (a policy)","launch into a diatribe"],"ex":"He delivered a long diatribe against the tax."},
"2023||insoluble": {"use":["insoluble in (water)","insoluble problem"],"ex":"The compound is insoluble in water."},
"2022||artifice": {"use":["use artifice","without artifice"],"ex":"Politicians use artifice to hide the truth."},
"2022||affront": {"use":["an affront to (justice)"],"ex":"The ruling is an affront to justice."},
"2022||vicissitude": {"use":["the vicissitudes of (life)"],"ex":"He endured the vicissitudes of life at sea."},
"2022||unheeded": {"use":["go unheeded"],"ex":"The warnings may go unheeded again."},
"2022||unrequited": {"use":["unrequited love"],"ex":"The poem is about unrequited love."},
"2022||unencumbered": {"use":["unencumbered by (debt)"],"ex":"She traveled unencumbered by heavy luggage."},
"2022||inexorable": {"use":["inexorable rise","inexorable decline"],"ex":"The inexorable rise of prices worried families."},
"2022||nonplussed": {"use":["nonplussed by (a question)"],"ex":"He was nonplussed by the sudden question."},
"2022||begrudge": {"use":["begrudge (someone) (their success)"],"ex":"I do not begrudge him his success."},
"2022||scruple": {"use":["scruples about (doing something)","without scruple"],"ex":"She had no scruples about lying."},
"2022||faux": {"use":["faux pas","faux fur"],"ex":"Wearing white to the wedding was a faux pas."},
"2022||acrimony": {"use":["acrimony between (two parties)","with acrimony"],"ex":"The acrimony between the partners grew worse."},
"2022||serendipity": {"use":["by serendipity","a stroke of serendipity"],"ex":"They met by serendipity at the airport."},
"2022||surfeit": {"use":["a surfeit of (something)"],"ex":"There was a surfeit of food at the party."},
"2022||eclectic": {"use":["eclectic mix","eclectic taste"],"ex":"The menu offers an eclectic mix of dishes."},
"2022||precipitous": {"use":["precipitous drop","precipitous decline"],"ex":"Stocks took a precipitous drop on Monday."},
"2022||astute": {"use":["astute observer","astute move"],"ex":"She is an astute observer of human nature."},
"2022||ingratiate": {"use":["ingratiate (oneself) with (someone)"],"ex":"He tried to ingratiate himself with the boss."},
"2022||languish": {"use":["languish in (prison)","languish at the bottom of (a table)"],"ex":"Many prisoners languish in jail for years."},
"2022||imprimatur": {"use":["the imprimatur of (an authority)","give (one's) imprimatur to (something)"],"ex":"The plan needs the imprimatur of the board."},
"2022||abscond": {"use":["abscond with (money)","abscond from (a place)"],"ex":"The clerk tried to abscond with the funds."},
"2022||quixotic": {"use":["quixotic quest","quixotic crusade"],"ex":"He set off on a quixotic quest for perfection."},
"2022||penchant": {"use":["a penchant for (something)"],"ex":"She has a penchant for dramatic hats."},
"2022||confer": {"use":["confer (an honor) on (someone)","confer with (someone)"],"ex":"The university will confer an honorary degree on her."},
"2022||chagrin": {"use":["to (one's) chagrin","with chagrin"],"ex":"To his chagrin, the store was closed."},
"2022||allay": {"use":["allay (fears)","allay (concerns)"],"ex":"The announcement helped to allay fears of a strike."},
"2022||distill": {"use":["distill (something) into (a summary)","distill (the essence) from (something)"],"ex":"The editor will distill the report into one page."},
"2022||obsequious": {"use":["obsequious to (superiors)","obsequious manner"],"ex":"He was obsequious to anyone with power."},
"2022||bifurcation": {"use":["bifurcation into (two parts)"],"ex":"Scientists noted the bifurcation into two separate lineages."},
"2022||paragon": {"use":["paragon of (virtue)"],"ex":"She was a paragon of patience."},
"2022||beguile": {"use":["beguiled by (charm)","beguile (someone) into (doing something)"],"ex":"The audience was beguiled by her voice."},
"2022||revile": {"use":["reviled as (a traitor)"],"ex":"He was reviled as a traitor."},
"2022||cunning": {"use":["cunning plan","cunning as a fox"],"ex":"She devised a cunning plan to win."},
"2022||adamant": {"use":["adamant about (something)","adamant that (clause)"],"ex":"She was adamant about leaving early."},
"2022||concatenation": {"use":["a concatenation of (events)"],"ex":"The disaster was a concatenation of small errors."},
"2022||hermetic": {"use":["hermetic seal"],"ex":"The jar has a hermetic seal."},
"2022||despotism": {"use":["enlightened despotism"],"ex":"The king ruled by enlightened despotism."},
"2022||aloof": {"use":["aloof from (others)","remain aloof"],"ex":"He kept aloof from office gossip."},
"2022||impugn": {"use":["impugn (someone's) integrity","impugn (someone's) motives"],"ex":"Do not impugn the integrity of the judge."},
"2022||placate": {"use":["placate (someone) with (a gift)"],"ex":"He tried to placate the crowd with promises."},
"2022||resplendent": {"use":["resplendent in (silk)","resplendent with (jewels)"],"ex":"She appeared resplendent in a crimson gown."},
"2022||vehement": {"use":["vehement protest","vehement denial"],"ex":"The plan met vehement protest."},
"2022||pariah": {"use":["pariah state","treat (someone) as a pariah"],"ex":"The regime became a pariah state."},
"2022||equable": {"use":["equable climate","equable temperament"],"ex":"The island has an equable climate."},
"2022||co-opt": {"use":["co-opt (someone) into (a group)"],"ex":"They tried to co-opt critics into the committee."},
"2022||inimitable": {"use":["inimitable style"],"ex":"She sang in her own inimitable style."},
"2022||replete": {"use":["replete with (details)"],"ex":"The report is replete with errors."},
"2022||temerity": {"use":["have the temerity to (object)"],"ex":"Few would have the temerity to ask for a raise."},
"2022||denizen": {"use":["denizens of (a place)"],"ex":"The denizens of the forest are shy."},
"2022||attest": {"use":["attest to (a fact)"],"ex":"Records attest to the town's long history."},
"2022||tacit": {"use":["tacit agreement","tacit approval"],"ex":"They reached a tacit agreement to avoid the topic."},
"2022||ergogenic": {"use":["ergogenic aid"],"ex":"Caffeine is a common ergogenic aid for athletes."},
"2022||excoriate": {"use":["excoriate (someone) for (a decision)"],"ex":"Critics excoriate the senator for his vote."},
"2022||dearth": {"use":["a dearth of (something)"],"ex":"There is a dearth of good teachers."},
"2022||unbridled": {"use":["unbridled enthusiasm","unbridled ambition"],"ex":"Fans greeted the team with unbridled enthusiasm."},
"2022||aplomb": {"use":["with aplomb"],"ex":"She handled the crisis with aplomb."},
"2022||laden": {"use":["laden with (supplies)"],"ex":"The cart was laden with fruit."},
"2022||pontificate": {"use":["pontificate about (politics)","pontificate on (a subject)"],"ex":"He likes to pontificate about politics."},
"2022||vitriol": {"use":["spew vitriol","vitriol against (a group)"],"ex":"Trolls often spew vitriol online."},
"2022||mollify": {"use":["mollify (someone) with (a gift)"],"ex":"He tried to mollify the customer with a refund."},
"2022||promulgate": {"use":["promulgate (a law)","promulgate (an idea)"],"ex":"The government will promulgate the new law next week."},
"2022||didactic": {"use":["didactic tone"],"ex":"The novel's didactic tone put off readers."},
"2022||reprisal": {"use":["in reprisal for (an attack)","reprisals against (civilians)"],"ex":"The village was burned in reprisal for the attack."},
"2022||fraught": {"use":["fraught with (danger)"],"ex":"The journey was fraught with danger."},
"2022||ardent": {"use":["ardent supporter","ardent admirer"],"ex":"He was an ardent supporter of reform."},
"2022||rapport": {"use":["rapport with (someone)","build rapport"],"ex":"She has a good rapport with her students."},
"2022||advent": {"use":["the advent of (the internet)"],"ex":"The advent of email changed office life."},
"2022||juncture": {"use":["at this juncture","at a critical juncture"],"ex":"At this juncture, we should reconsider the plan."},
"2022||boon": {"use":["a boon to (someone)"],"ex":"The new road is a boon to local shops."},
"2022||pedigree": {"use":["of impeccable pedigree","pedigree dog"],"ex":"The horse is of impeccable pedigree."},
"2022||conveyance": {"use":["means of conveyance","conveyance of (goods)"],"ex":"A cart was their only means of conveyance."},
"2022||inimical": {"use":["inimical to (growth)"],"ex":"Such policies are inimical to growth."},
"2022||demarcation": {"use":["demarcation line","demarcation between (two things)"],"ex":"The river forms a demarcation line between the states."},
"2022||morass": {"use":["a morass of (details)","bogged down in a morass"],"ex":"The case sank into a morass of legal detail."},
"2022||furor": {"use":["furor over (a decision)"],"ex":"The decision sparked a furor over fairness."},
"2022||consign": {"use":["consign (something) to (the past)"],"ex":"They want to consign the old rules to history."},
"2022||milieu": {"use":["social milieu","cultural milieu"],"ex":"She grew up in a rich social milieu."},
"2022||scourge": {"use":["the scourge of (poverty)"],"ex":"Malaria remains the scourge of many regions."},
"2022||recant": {"use":["recant (a statement)","recant (one's testimony)"],"ex":"The witness agreed to recant his statement."},
"2022||detente": {"use":["detente between (two powers)"],"ex":"A detente between the two powers eased tensions."},
"2022||antipathy": {"use":["antipathy toward (someone)","antipathy to (something)"],"ex":"He felt a deep antipathy toward crowds."},
"2022||furlough": {"use":["on furlough","furlough (workers)"],"ex":"Many staff were placed on furlough during the shutdown."},
"2022||modicum": {"use":["a modicum of (respect)"],"ex":"Show a modicum of respect."},
"2022||pall": {"use":["pall on (someone)","cast a pall over (something)"],"ex":"Fast food can quickly pall on you."},
"2022||scrupulous": {"use":["scrupulous about (details)","scrupulous attention to (detail)"],"ex":"She is scrupulous about safety."},
"2022||purveyor": {"use":["purveyor of (fine goods)"],"ex":"The shop is a purveyor of fine teas."},
"2022||defray": {"use":["defray (the cost of)","defray (expenses)"],"ex":"Donations help defray the cost of repairs."},
"2022||pejorative": {"use":["pejorative term","pejorative sense"],"ex":"It is a pejorative term for retirees."},
"2022||espouse": {"use":["espouse (a cause)","espouse (a belief)"],"ex":"Many scientists espouse the new theory."},
"2022||countervail": {"use":["countervailing force","countervailing duty"],"ex":"A countervailing force balanced the market."},
"2022||internecine": {"use":["internecine conflict","internecine warfare"],"ex":"Internecine conflict weakened the party."},
"2022||bastion": {"use":["bastion of (freedom)"],"ex":"The college is a bastion of tradition."},
"2022||zeitgeist": {"use":["capture the zeitgeist","zeitgeist of (an era)"],"ex":"The film seems to capture the zeitgeist of the 1990s."},
"2022||apparatus": {"use":["state apparatus","security apparatus"],"ex":"The state apparatus controlled the press."},
"2022||shill": {"use":["shill for (a company)"],"ex":"Critics call him a shill for the industry."},
"2022||stochastic": {"use":["stochastic process","stochastic model"],"ex":"Weather is modeled as a stochastic process."},
"2021||seminal": {"use":["seminal work","seminal paper"],"ex":"Her seminal work reshaped the field."},
"2021||syndicate": {"use":["crime syndicate","syndicate of (investors)"],"ex":"Police broke up a crime syndicate in the port city."},
"2021||disparate": {"use":["disparate groups","disparate elements"],"ex":"The coalition unites disparate groups."},
"2021||engender": {"use":["engender (trust)","engender (a feeling) in (someone)"],"ex":"Honesty can engender trust among colleagues."},
"2021||specious": {"use":["specious argument","specious reasoning"],"ex":"Her specious argument fooled no one."},
"2021||accost": {"use":["accost (someone) in (the street)"],"ex":"A stranger tried to accost her in the street."},
"2021||derision": {"use":["be met with derision","an object of derision"],"ex":"The plan is likely to be met with derision."},
"2021||exigency": {"use":["the exigencies of (war)"],"ex":"The exigencies of war forced new rules on the town."},
"2021||congenial": {"use":["congenial company","congenial to (someone)"],"ex":"They enjoyed congenial company at dinner."},
"2021||haphazard": {"use":["in a haphazard fashion"],"ex":"The books were stacked in a haphazard fashion."},
"2021||deft": {"use":["deft at (a task)","deft touch"],"ex":"She is deft at handling difficult clients."},
"2021||buttress": {"use":["buttress (an argument) with (evidence)"],"ex":"He tried to buttress his claim with data."},
"2021||collate": {"use":["collate (data) from (sources)","collate (A) with (B)"],"ex":"She will collate the reports from each branch."},
"2021||impregnable": {"use":["impregnable fortress","impregnable defense"],"ex":"The castle was an impregnable fortress."},
"2021||paucity": {"use":["paucity of (evidence)"],"ex":"A paucity of evidence weakened the case."},
"2021||depredation": {"use":["the depredations of (invaders)"],"ex":"Farmers suffered the depredations of invading armies."},
"2021||salutary": {"use":["salutary lesson","salutary effect"],"ex":"The defeat was a salutary lesson for the team."},
"2021||abate": {"use":["no sign of abating","abate (a storm, pain)"],"ex":"The rain showed no sign of abating."},
"2021||lurid": {"use":["lurid details","lurid headline"],"ex":"The tabloid printed lurid details of the trial."},
"2021||provenance": {"use":["of unknown provenance","provenance of (an artwork)"],"ex":"The painting is of unknown provenance."},
"2021||consummate": {"use":["consummate professional","consummate skill"],"ex":"She is a consummate professional."},
"2021||exculpate": {"use":["exculpate (someone) from (blame)"],"ex":"The new evidence may exculpate him from blame."},
"2021||stultify": {"use":["stultifying routine","stultifying atmosphere"],"ex":"He fled the stultifying routine of office life."},
"2021||posterity": {"use":["for posterity","preserve (something) for posterity"],"ex":"The diaries were kept for posterity."},
"2021||vitiate": {"use":["vitiated by (a flaw)","vitiate (a contract)"],"ex":"The whole study was vitiated by bias."},
"2021||purport": {"use":["purport to (be something)","purported (author, cure)"],"ex":"The document purports to be an official record."},
"2021||hubris": {"use":["hubris of (a leader)","tragic hubris"],"ex":"The hubris of the founders doomed the company."},
"2021||deign": {"use":["deign to (reply)"],"ex":"He would not deign to answer the question."},
"2021||amalgamate": {"use":["amalgamate with (another)","amalgamate into (one)"],"ex":"The two banks agreed to amalgamate with each other."},
"2021||respite": {"use":["respite from (something)","without respite"],"ex":"The cabin offered respite from the noise."},
"2021||injunction": {"use":["injunction against (a company)","issue an injunction"],"ex":"The court granted an injunction against the company."},
"2021||eminent": {"use":["eminent scholar","eminent domain"],"ex":"An eminent scholar gave the lecture."},
"2021||triage": {"use":["triage (patients)","triage nurse"],"ex":"Nurses triage patients as they arrive."},
"2021||enmity": {"use":["enmity between (two groups)","enmity toward (someone)"],"ex":"Long enmity between the families finally ended."},
"2021||incisive": {"use":["incisive analysis","incisive comment"],"ex":"Her incisive analysis exposed the flaw."},
"2021||iniquity": {"use":["den of iniquity"],"ex":"The old tavern was called a den of iniquity."},
"2021||intractable": {"use":["intractable problem","intractable conflict"],"ex":"The team faced an intractable problem."},
"2021||beleaguered": {"use":["beleaguered by (critics)"],"ex":"The firm, beleaguered by lawsuits, finally closed."},
"2021||quid pro quo": {"use":["a quid pro quo for (something)"],"ex":"The deal was a quid pro quo for his vote."},
"2021||laudable": {"use":["laudable goal","laudable effort"],"ex":"Reducing waste is a laudable goal."},
"2021||disrepute": {"use":["bring (something) into disrepute","fall into disrepute"],"ex":"Such behavior could bring the club into disrepute."},
"2021||consternation": {"use":["in consternation","to (someone's) consternation"],"ex":"The crowd stared in consternation."},
"2021||apotheosis": {"use":["apotheosis of (a style)"],"ex":"The cathedral is the apotheosis of Gothic design."},
"2021||pithy": {"use":["pithy remark","pithy saying"],"ex":"He ended the talk with a pithy remark."},
"2021||putative": {"use":["putative father","putative cause"],"ex":"The court named the putative father."},
"2021||surmise": {"use":["surmise that (clause)","surmise from (evidence)"],"ex":"From the footprints, we can surmise that he left early."},
"2021||reckoning": {"use":["day of reckoning","by (one's) reckoning"],"ex":"The scandal brought a day of reckoning."},
"2021||reticent": {"use":["reticent about (one's past)"],"ex":"He was reticent about his past."},
"2021||machination": {"use":["the machinations of (a rival)","political machinations"],"ex":"She fell victim to the machinations of her rivals."},
"2021||eloquent": {"use":["eloquent on (a subject)","eloquent testimony to (something)"],"ex":"She was eloquent on the subject of justice."},
"2021||propitious": {"use":["propitious for (a plan)","propitious moment"],"ex":"The weather was propitious for sailing."},
"2021||latent": {"use":["latent talent","latent heat"],"ex":"The program uncovered latent talent in students."},
"2021||thrall": {"use":["in thrall to (someone)"],"ex":"The party is in thrall to its donors."},
"2021||inveterate": {"use":["inveterate liar","inveterate gambler"],"ex":"He was an inveterate liar."},
"2021||ignominy": {"use":["the ignominy of (defeat)"],"ex":"He could not bear the ignominy of defeat."},
"2020||profligate": {"use":["profligate with (money)","profligate spending"],"ex":"The council was profligate with public money."},
"2020||aspersion": {"use":["cast aspersions on (someone)"],"ex":"Do not cast aspersions on his honesty."},
"2020||faculty": {"use":["faculty of (speech)","mental faculties"],"ex":"He lost the faculty of speech."},
"2020||subvert": {"use":["subvert (authority)","subvert (the government)"],"ex":"Spies tried to subvert the government."},
"2020||heuristic": {"use":["heuristic method","heuristic approach"],"ex":"She used a heuristic method to guess the answer."},
"2020||aberration": {"use":["aberration from (the norm)"],"ex":"The result was an aberration from the norm."},
"2020||tenuous": {"use":["tenuous link","tenuous connection"],"ex":"The two events have only a tenuous link."},
"2020||fickle": {"use":["fickle weather","fickle fans"],"ex":"Fickle weather ruined the picnic."},
"2020||ineffable": {"use":["ineffable beauty","ineffable sadness"],"ex":"The music had an ineffable beauty."},
"2020||pretext": {"use":["on the pretext of (doing something)","under the pretext that (clause)"],"ex":"He left early on the pretext of a headache."},
"2020||assiduous": {"use":["assiduous in (one's duties)","assiduous attention to (detail)"],"ex":"She was assiduous in her duties."},
"2020||desultory": {"use":["desultory conversation","desultory effort"],"ex":"They made desultory conversation over coffee."},
"2020||trepidation": {"use":["with trepidation","trepidation about (something)"],"ex":"She opened the letter with trepidation."},
"2020||ostensible": {"use":["ostensible reason","ostensible purpose"],"ex":"The ostensible reason for the trip was business."},
"2020||perverse": {"use":["perverse incentive","perverse pleasure"],"ex":"The rule creates a perverse incentive to cheat."},
"2020||zeal": {"use":["zeal for (a cause)","with zeal"],"ex":"He showed great zeal for the cause."},
"2020||frivolous": {"use":["frivolous lawsuit","frivolous spending"],"ex":"The court dismissed the frivolous lawsuit."},
"2020||equanimity": {"use":["with equanimity","accept (a setback) with equanimity"],"ex":"She took the news with equanimity."},
"2020||reprise": {"use":["a reprise of (a theme)","reprise (a role)"],"ex":"The finale is a reprise of the opening theme."},
"2020||portent": {"use":["portent of (disaster)"],"ex":"The dark clouds were a portent of disaster."},
"2020||pedantic": {"use":["pedantic about (details)"],"ex":"He is pedantic about grammar."},
"2020||ostentatious": {"use":["ostentatious display","ostentatious wealth"],"ex":"The party was an ostentatious display of wealth."},
"2020||pretense": {"use":["under false pretenses","make a pretense of (doing something)"],"ex":"He got the money under false pretenses."},
"2020||disport": {"use":["disport (oneself) in (a place)"],"ex":"Children disport themselves in the shallow waves."},
"2020||propagate": {"use":["propagate by (cuttings)","propagate (an idea)"],"ex":"Many shrubs propagate by cuttings."},
"2020||commensurate": {"use":["commensurate with (experience)"],"ex":"Pay will be commensurate with experience."},
"2020||abdicate": {"use":["abdicate (the throne)","abdicate responsibility for (something)"],"ex":"The king chose to abdicate the throne."},
"2020||nascent": {"use":["nascent industry","nascent democracy"],"ex":"The nascent industry needed investment."},
"2020||exhortation": {"use":["exhortation to (act)"],"ex":"Her exhortation to keep going inspired the team."},
"2020||vestigial": {"use":["vestigial organ","vestigial tail"],"ex":"The appendix is often called a vestigial organ."},
"2020||menial": {"use":["menial job","menial task"],"ex":"He took a menial job to pay the rent."},
"2020||cursory": {"use":["cursory glance","cursory inspection"],"ex":"He gave the page only a cursory glance."},
"2020||credulity": {"use":["strain credulity"],"ex":"That excuse would strain credulity."},
"2020||extricate": {"use":["extricate (oneself) from (trouble)"],"ex":"It took months to extricate the company from debt."},
"2020||amenable": {"use":["amenable to (suggestion)"],"ex":"He was amenable to suggestion."},
"2020||affinity": {"use":["affinity for (something)","affinity with (someone)","affinity between (two things)"],"ex":"She has a natural affinity for languages."},
"2020||volition": {"use":["of (one's) own volition"],"ex":"He left of his own volition."},
"2020||untenable": {"use":["untenable position","untenable situation"],"ex":"The untenable position forced him to resign."},
"2020||stipulate": {"use":["stipulate that (clause)"],"ex":"The contract may stipulate that payment is due in full."},
"2020||iterate": {"use":["iterate on (a design)"],"ex":"Teams iterate on the prototype each week."},
"2020||entrenched": {"use":["entrenched in (a belief)","deeply entrenched"],"ex":"Old habits are entrenched in the culture."},
"2020||auspicious": {"use":["auspicious start","auspicious occasion"],"ex":"The season had an auspicious start."},
"2020||poignant": {"use":["poignant reminder","poignant moment"],"ex":"The photo was a poignant reminder of home."},
"2020||sanguine": {"use":["sanguine about (the future)"],"ex":"She stays sanguine about the outcome."},
"2020||propriety": {"use":["a sense of propriety","with propriety"],"ex":"She has a sense of propriety."},
"2020||quandary": {"use":["in a quandary about (what to do)"],"ex":"He was in a quandary about what to do."},
"2020||pragmatic": {"use":["pragmatic approach","pragmatic about (something)"],"ex":"She took a pragmatic approach to the problem."},
"2020||veracity": {"use":["veracity of (a claim)","question the veracity of (a claim)"],"ex":"Few people doubted the veracity of the report."},
"2020||abeyance": {"use":["in abeyance","fall into abeyance"],"ex":"The plan was held in abeyance."},
"2020||qualm": {"use":["qualms about (doing something)","have no qualms about"],"ex":"He had no qualms about lying."},
"2020||rash": {"use":["rash decision","rash promise"],"ex":"It was a rash decision to quit."},
"2020||fastidious": {"use":["fastidious about (details)"],"ex":"He is fastidious about his appearance."},
"2020||furtive": {"use":["furtive glance","furtive look"],"ex":"She cast a furtive glance at the door."},
"2020||impunity": {"use":["with impunity","act with impunity"],"ex":"Thieves operated with impunity for years."}
};
